#!/bin/bash
# This is a test. This DOES NOT work!

currdir=`pwd`
ircpp=`find ~/R -name 'Rcpp' | head -1`
ircpparma=`find ~/R -name 'RcppArmadillo' | head -1`

g++ -I/usr/share/R/include -DNDEBUG    -I"$ircpp/include" -I"$ircpparma/include" -I"$currdir"   -std=c++11 -fpic  -O3 -pipe  -g  -c dppois.cpp -o dppois.o

g++ -shared -o dppois.so dppois.o -llapack -lblas -lgfortran -lm -lquadmath -L/usr/lib/R/lib -lR

