#!/bin/bash
# This is a test. This DOES NOT work!

g++ -I/usr/share/R/include -DNDEBUG    -I"/home/arthur/R/x86_64-pc-linux-gnu-library/3.0/Rcpp/include" -I"/home/arthur/R/x86_64-pc-linux-gnu-library/3.0/RcppArmadillo/include" -I"/home/arthur/Repo/bnp_HW/02_dpmm/code/Rcpp"   -std=c++11 -fpic  -O3 -pipe  -g  -c dppois.cpp -o dppois.o

g++ -shared -o dppois.so dppois.o -llapack -lblas -lgfortran -lm -lquadmath -L/usr/lib/R/lib -lR

