#!/bin/bash
# For dp assignment

argnum=$#

currdir=`pwd`
if [ "$argnum" -eq "0" ]
then
  echo "You need to enter a file name"
else
  file="$1"
  path=`pwd | sed 's/home\/arthur/soe\/alui2/'` 
  pathtofile=$path$file
  echo $pathtofile

#gush
#ssh alui2@citrisdance.soe.ucsc.edu << EOF
#  cd ~/bnp_hw/
#  git pull
#  R CMD BATCH $pathtofile
#EOF
#
#  `scp -r alui2@citrisdance.soe.ucsc.edu:/soe/alui2/bnp_hw/01_dp_priors/code/pdfs /home/arthur/bnp_hw/01_dp_priors/code/pdfs`
#  cd ~/bnp_hw/01_dp_priors/latex
#  comptex
#  cd currdir
fi

